CREATE USER struts10 IDENTIFIED BY struts10;
GRANT CONNECT, RESOURCE TO struts10;

CONNECT struts10/struts10

DROP TABLE RESERVA;
DROP SEQUENCE RESERVA_SEQ;

CREATE SEQUENCE RESERVA_SEQ;

CREATE TABLE RESERVA
(NUMERO                    NUMBER(4) PRIMARY KEY,
 ENDERECO_EMAIL            VARCHAR2(30),
 COR                       VARCHAR2(08),
 TETO_SOLAR                NUMBER(1),
 VIDRO_ELETRICO            NUMBER(1),
 PORTAS                    CHAR(1),
 VALOR_LOCACAO             NUMBER(9,2),
 DATA_LOCACAO              DATE,
 AGENCIA                   VARCHAR2(10));

DROP TABLE COR;
DROP SEQUENCE COR_SEQ;

CREATE SEQUENCE COR_SEQ;

CREATE TABLE COR
(ID                        NUMBER(4) PRIMARY KEY,
 LABEL                     VARCHAR2(15),
 VALOR                     VARCHAR2(15));

INSERT INTO COR
VALUES(COR_SEQ.NEXTVAL, 'Azul', 'azul');

INSERT INTO COR
VALUES(COR_SEQ.NEXTVAL, 'Vermelho', 'vermelho');

INSERT INTO COR
VALUES(COR_SEQ.NEXTVAL, 'Verde', 'verde');

COMMIT;

